export enum residentialInfo {
  imageSrc_01 = "/residentialPage_Icon_01.png",
  imageSrc_02 = "/residentialPage_Icon_02.png",
  imageSrc_03 = "/residentialPage_Icon_03.png",
  imageSrc_04 = "/residentialPage_Icon_04.png",
  image_01_Text_EN = "Harmonic Architecture",
  image_01_Text_ES = "Arquitectura Armónica",
  title_01_EN = "PARK STREET + Strategic Alliance",
  title_01_ES = "PARK STREET + Alianza Estratégica",
  title_02_EN = "Ideal, Exclusive and Intelligent Distribution",
  title_02_ES = "Distribución Ideal,  Exclusiva e Inteligente",
  title_03_EN = "FEATURES",
  title_03_ES = "CARACTERÍSTICAS",
  title_04_EN = "COMING SOON",
  title_04_ES = "PRÓXIMAMENTE",

  info_01_EN = "We gathered the best designers in the city, with the aim of creating a different, unique, exclusive and harmonious environment to ensure good taste, value and unit development.",
  info_01_ES = "Reunimos los mejores diseñadores de la ciudad, con el objetivo de crear un entorno diferente, único, exclusivo y armónico, para asegurar el buen gusto, plusvalía y la unidad del desarrollo.",
  info_02_EN = "PARK STREET creates a strategic alliance with the best designers of the RGV, projecting high-impact design for the environment in APPLE WOODS",
  info_02_ES = "PARK STREET crea una alianza estratégica con los mejores diseñadores del RGV, proyectando diseño de alto impacto para el entorno en APPLE WOODS",
  info_03_title_EN = "Pre-sale purchase and additional costs are on us",
  info_03_title_ES = "Compra en Pre-Venta y los costos adicionales van por nuestra cuenta",
  info_03_text_EN = "In its initial stage, APPLE WOODS offers 49 residential lots that feature exclusive indoor and outdoor amenities.",
  info_03_text_ES = "En su etapa inicial, APPLE WOODS ofrece 49 lotes residenciales que cuentancon amenidades exclusivas, interior y exterior.",
  info_04_EN = "For the beginning of this stage, a new housing concept has been developed where spaces are optimized, maintaining functionality and exclusivity in common areas",
  info_04_ES = "Para el comienzo de esta etapa, se ha desarrollado un nuevo concepto de vivienda donde se optimizan espacios, manteniendo la funcionalidady exclusividad en áreas comunes",
  info_05_title_EN = "LOT:",
  info_05_title_ES = "Terreno:",
  info_05_text_EN = "Minimum 6000ft2. General 60’ x 100+9’",
  info_05_text_ES = "Mínimo 6000ft2. Generalmente 60’ x 100+9’",
  info_06_title_EN = "Construction:",
  info_06_title_ES = "Construcción:",
  info_06_text_EN = "Area: 50’ x 65’ x (1-3) / Minimum Construction: 2,000 Ft..2 (garage included)",
  info_06_text_ES = "Area: 50’ x 65’ x (1-3)   /  Mínimo a Construír: 2,000 Ft..2 (incluye cochera)",
}

export const information_07 = {
  title_EN: "Residential Complex:",
  title_ES: "Complejo Residencial:",
  points_EN: [
    "• Common areas Entrance gates",
    "• Fountains and landscaping",
    "• Club membership",
    "• Clubhouse use",
    "• 50% OFF in use of lounges and event areas",
  ],
  points_ES: [
    "• Areas comunesPortones de entrada",
    "• Fuentes y jardinería",
    "• Membresía de club",
    "• Uso de casa club",
    "• 50% OFF en uso de salones y áreas de eventos",
  ],
};

export const information_08 = {
  title_EN: "Residency:",
  title_ES: "Residencia:",
  points_EN: [
    "• Decorative bench 4 'x 60'",
    "• Fine grass 99.9% homogeneous",
    "• Two smart 'decora' switches",
    "• Side fences",
    "• Fruit tree",
    "• Decorative gardening in front",
  ],
  points_ES: [
    "• Banqueta decorativa de 4’ x 60’",
    "• Césped fino 99.9% homogéneo",
    "• Dos interruptores tipo “decora” inteligentes",
    "• Cercas laterales",
    "• Árbol frutal",
    "• Jardinería Decorativa al frente",
  ],
};
